### ISSUE TITLE
iOS Tips

### ISSUE THREAD

**Issue by wangwangwar** [wangwangwar/daily-notes#56]
在APP中打开设置页面以及一级二级菜单方法：

``` Objective-C
 [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"prefs:root=General"]];
```

需要在APP工程中设置一下：
在Xcode中打开工程设置页面 - Info - URL Types
中添加 "URL Schemes - prefs" 

http://stackoverflow.com/questions/8246070/ios-launching-settings-restrictions-url-scheme

**Comment by sauchye** [comment]
@wangwangwar  闯锅搞点RAC教程涨涨姿势啊
